language: python
python:
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -r dev_requirements.txt --use-mirrors
script:
  - coverage run --source=djqscsv setup.py test
after_success:
  - coveralls
