language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
script:
  - coverage run --source=djqscsv tests/__init__.py
after_success:
  - coveralls
